    def toggle_topic_visibility(self, display_name: str, topic: str) -> dict[str, Any]: ...
    def get_topic_visibility(self, display_name: str) -> dict[str, Any]: ...
    def view_presets(self) -> dict[str, Any]: ...
    def set_view_preset(self, name: str) -> dict[str, Any]: ...
    def display_properties(self, display_name: str) -> dict[str, Any]: ...
    def update_display_properties(self, display_name: str, color: list[float] | None = None, size: float | None = None, alpha: float | None = None) -> dict[str, Any]: ...
